version: "3.7"

services:
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  nmdc_dagster_postgresql:
    image: postgres:11
    container_name: nmdc_dagster_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - nmdc_dagster_network

  # This service runs the gRPC server that loads and executes your pipelines, in both dagit
  # and dagster-daemon. By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the
  # run launcher to use this same image when launching runs in a new container as well.
  # Multiple containers like this can be deployed separately - each just needs to run on
  # its own port, and have its own entry in the workspace.yaml file that's loaded by dagit.
  nmdc_dagster_pipelines:
    build:
      context: ..
      dockerfile: nmdc_runtime/pipelines.Dockerfile
    container_name: nmdc_dagster_pipelines
    image: nmdc_dagster_pipelines_image
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "nmdc_dagster_pipelines_image"
    networks:
      - nmdc_dagster_network

  # This service runs dagit, which loads the pipelines from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from dagit will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  nmdc_dagster_dagit:
    build:
      context: .
      dockerfile: ./dagster.Dockerfile
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: nmdc_dagster_dagit
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    networks:
      - nmdc_dagster_network
    depends_on:
      - nmdc_dagster_postgresql
      - nmdc_dagster_pipelines

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  nmdc_dagster_daemon:
    build:
      context: .
      dockerfile: ./dagster.Dockerfile
    entrypoint:
      - dagster-daemon
      - run
    container_name: nmdc_dagster_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nmdc_dagster_network
    depends_on:
      - nmdc_dagster_postgresql
      - nmdc_dagster_pipelines

networks:
  nmdc_dagster_network:
    driver: bridge
    name: nmdc_dagster_network
